=== KeziaTirza/webservice/perhotelan/bin/perhotelan.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="perhotelan">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="datatamu"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="datatamu">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="tamu"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="tamu">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nama"/>
                <xs:element ref="jeniskelamin"/>
                <xs:element ref="kotaasal"/>
                <xs:element ref="no.hp"/>
                <xs:element ref="alasan_menginap"/>
                <xs:element ref="kamar"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="nama">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:NCName">
                    <xs:attribute name="sebutan" use="required" type="xs:NCName"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="jeniskelamin" type="xs:NCName"/>
    <xs:element name="kotaasal" type="xs:NCName"/>
    <xs:element name="no.hp">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:integer">
                    <xs:attribute name="code" use="required" type="xs:integer"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="alasan_menginap" type="xs:NCName"/>
    <xs:element name="kamar">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="kode" minOccurs="1"/>
                <xs:element ref="nama_kamar"/>
                <xs:element ref="lama_sewa"/>
                <xs:element ref="harga"/>
                <xs:element ref="jumlah_orang"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="kode" type="xs:NCName"/>
    <xs:element name="nama_kamar" type="xs:NCName"/>
    <xs:element name="lama_sewa" type="xs:NCName"/>
    <xs:element name="harga">
    	<xs:simpleType>
    		<xs:restriction base="xs:integer">

    			<xs:minInclusive value="10000"></xs:minInclusive>
    		</xs:restriction>
    	</xs:simpleType>
    </xs:element>
    <xs:element name="jumlah_orang" type="xs:integer"/>
</xs:schema>

=== KeziaTirza/webservice/perhotelan/src/perhotelan.xml
<?xml version="1.0" encoding="UTF-8"?> 
<perhotelan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="perhotelan.xsd"> 
<datatamu>
<tamu>
	<nama sebutan="Ms.">Kezia</nama>
	<jeniskelamin>Perempuan</jeniskelamin>
	<kotaasal>Kupang</kotaasal>
	<no.hp code="+62">1353226745</no.hp>
	<alasan_menginap>Liburan</alasan_menginap>
	<kamar>
		<kode>A01</kode>
		<nama_kamar>Melati</nama_kamar>
		<lama_sewa>perhari</lama_sewa>
		<harga>500000</harga>
		<jumlah_orang>2</jumlah_orang>
	</kamar>
</tamu>
</datatamu>

<datatamu>
<tamu>
	<nama sebutan="Mr.">Bene</nama>
	<jeniskelamin>Laki-laki</jeniskelamin>
	<kotaasal>Medan</kotaasal>
	<no.hp code="+62">1353445678</no.hp>
	<alasan_menginap>Liburan</alasan_menginap>
	<kamar>
		<kode>A02</kode>
		<nama_kamar>Mawar</nama_kamar>
		<lama_sewa>perhari</lama_sewa>
		<harga>600000</harga>
		<jumlah_orang>1</jumlah_orang>
	</kamar>
</tamu>
</datatamu>

<datatamu>
<tamu>
	<nama sebutan="Mr.">Jhon</nama>
	<jeniskelamin>Laki-laki</jeniskelamin>
	<kotaasal>Medan</kotaasal>
	<no.hp code="+62">189736478</no.hp>
	<alasan_menginap>Liburan</alasan_menginap>
	<kamar>
		<kode>A03</kode>
		<nama_kamar>Kamboja</nama_kamar>
		<lama_sewa>perhari</lama_sewa>
		<harga>500000</harga>
		<jumlah_orang>2</jumlah_orang>
	</kamar>
</tamu>
</datatamu>

<datatamu>
<tamu>
	<nama sebutan="Ms.">Aya</nama>
	<jeniskelamin>Perempuan</jeniskelamin>
	<kotaasal>Bekasi</kotaasal>
	<no.hp code="+62">1320453124</no.hp>
	<alasan_menginap>Liburan</alasan_menginap>
	<kamar>
		<kode>A04</kode>
		<nama_kamar>Bougenvil</nama_kamar>
		<lama_sewa>perhari</lama_sewa>
		<harga>500000</harga>
		<jumlah_orang>3</jumlah_orang>
	</kamar>
</tamu>
</datatamu>

<datatamu>
<tamu>
	<nama sebutan="Ms.">Dila</nama>
	<jeniskelamin>Perempuan</jeniskelamin>
	<kotaasal>Sulawesi</kotaasal>
	<no.hp code="+62">1320453123</no.hp>
	<alasan_menginap>Pekerjaan</alasan_menginap>
	<kamar>
		<kode>A05</kode>
		<nama_kamar>Anggrek</nama_kamar>
		<lama_sewa>perhari</lama_sewa>
		<harga>500000</harga>
		<jumlah_orang>3</jumlah_orang>
	</kamar>
</tamu>
</datatamu>

<datatamu>
<tamu>
	<nama sebutan="Ms.">Pebri</nama>
	<jeniskelamin>Perempuan</jeniskelamin>
	<kotaasal>Sarijadi</kotaasal>
	<no.hp code="+62">1320453123</no.hp>
	<alasan_menginap>Kerja</alasan_menginap>
	<kamar>
		<kode>A06</kode>
		<nama_kamar>Kamboja</nama_kamar>
		<lama_sewa>perhari</lama_sewa>
		<harga>700000</harga>
		<jumlah_orang>3</jumlah_orang>
	</kamar>
</tamu>
</datatamu>
</perhotelan>
